### ISSUE TITLE
Add homebrew cask support

### ISSUE THREAD

**Issue by evilsprut** [brunophilipe/Cakebrew#161] opened 2016-01-28 07:32 UTC
Hello! Can you add [homebrew cask](http://caskroom.io) support?

> Homebrew Cask extends Homebrew and brings its elegance, simplicity, and speed to OS X applications and large binaries alike.

**Comment by brunophilipe** [comment] 2016-01-28 21:38
Duplicate of https://github.com/brunophilipe/Cakebrew/issues/76

**Closed by brunophilipe** 2016-01-28 21:38 UTC
