### ISSUE TITLE
Crash when click items

### ISSUE THREAD

**Issue by yangyaofei** [brunophilipe/Cakebrew#194] opened 2017-06-27 08:35 UTC
Crash when i search mysql-connector an click the item 

there is the crash info:

[Cakebrew_2017-06-27-162519_yangyaofeideMacBook.txt](https://github.com/brunophilipe/Cakebrew/files/1104668/Cakebrew_2017-06-27-162519_yangyaofeideMacBook.txt)

**Comment by brunophilipe** [comment] 2017-06-30 22:53
Duplicate of #195, fixed. Thanks! 👍

**Closed by brunophilipe** 2017-06-30 22:53 UTC
