### ISSUE TITLE
Cakebrew won't update

### ISSUE THREAD

**Issue by greenchapter** [brunophilipe/Cakebrew#149] opened 2015-10-14 22:48 UTC
When I would update I get this message.

<img width="547" alt="bildschirmfoto 2015-10-14 um 23 56 40" src="https://cloud.githubusercontent.com/assets/693276/10500151/57cd558c-72d6-11e5-857f-e7ed1eb2fcdb.png">
It's in german

**Comment by brunophilipe** [comment] 2015-10-16 19:41
Please check if the error persists. It could have been a network timeout (which is strange because my server is hosted in Germany, but anyway).

**Comment by davidspiess** [comment] 2015-10-25 10:46
I get the same error (german).

**Comment by blazejhadzik** [comment] 2015-10-28 14:03
Same here.

**Comment by brunophilipe** [comment] 2015-10-29 00:42
Fixed in commit 557845c0be3a58982f31a08149794b2658e660f8.
It was caused by App Transport Security blocking cleartext HTTP connections in El Capitan, but now I've changed everything to use HTTPS. However, the 1.1.4 version still has the http link to the update feed, so you will have to download version 1.1.5 from the Cakebrew website. But after that, you're all set! Thanks for the patience. :smiley:

**Closed by brunophilipe** 2015-10-29 00:42 UTC
