### ISSUE TITLE
brew cask install fails

### ISSUE THREAD

**Issue by tdiethe** [brunophilipe/Cakebrew#191] opened 2017-05-09 13:21 UTC
```
brew cask install cakebrew
==> Downloading https://cdn.cakebrew.com/cakebrew-1.2.3.dmg

curl: (60) SSL certificate problem: Invalid certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
Error: Download failed on Cask 'cakebrew' with message: Download failed: https://cdn.cakebrew.com/cakebrew-1.2.3.dmg
The incomplete download is cached at /Users/td6301/Library/Caches/Homebrew/Cask/cakebrew--1.2.3.dmg.incomplete
Error: nothing to install
```

**Comment by brunophilipe** [comment] 2017-05-09 13:31
This is an issue for Cask, and is a duplicate of #187.

Running `brew update` before trying to install should fix the problem.

**Closed by brunophilipe** 2017-05-09 13:31 UTC
